    
import pyautogui
import subprocess
import time

def perform_actions(tab_count):
    brave_executable = '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser'
    subprocess.Popen([brave_executable])
    time.sleep(2)
    pyautogui.press('\t', presses=tab_count)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(5)   
    pyautogui.click()
    time.sleep(2)
    pyautogui.hotkey('command', 't')
    pyautogui.click()
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)   
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)
    pyautogui.hotkey('command', 'r')
    time.sleep(2)
    pyautogui.scroll(-20)
    time.sleep(2)
    pyautogui.scroll(-15)
    time.sleep(2)


tab_counts = [1,4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,52]
for tab_count in tab_counts:
    perform_actions(tab_count)
    pyautogui.hotkey('command', 'w')
    pyautogui.hotkey('command', 'w')
